### ISSUE TITLE
建议添加快捷键 home 和 最小化到 任务栏里面

### ISSUE THREAD

**Issue by lyy33441314** [lalakii/MouseClickTool#5]
建议添加快捷键 home 和 最小化到 任务栏里面

**Comment by ttlttc** [comment]
建议配置写在ini当个绿色版

**Comment by lalakii** [comment]
> 建议配置写在ini当个绿色版

配置文件在 %TEMP% 路径下，就是绿色版，我想在代码里面很容易就能看出来。

https://github.com/lalakii/MouseClickTool/blob/master/MouseClickTool.cs#L275
